[SCHEMA] Tests for render listings
bids-standard/bids-specification pull request #1018
Opened 2022-02-28 09:29 UTC by TheChymera

As discussed in last week's meeting.

Turns out this is a bit more tricky than I thought, because the outputs are large blocks of text which are hard to test w/o reproducing the code that created them or hard-coding output (which will automatically “break” whenever the schema is meaningfully changed — so of limited use, really, and a bit of a chore to re-write for schema contributors).

I tried to hard-code only small stable bits, and come up with some sanity/consistency checks.
Better than nothing, but really doesn't cover all the possible failures of the functions...

Another approach would be to assert line number or checksums — that would be less of a chore to update, but still of limited use since they would need to be updated very frequently.

In any case it's moderately useful as is for the addition of regex support which I wanted to do.
And testing regex consistency will in any case be easier than testing human-readable output. 

@tsalo — thoughts?

2022-03-17 20:09 UTC, TheChymera commented
@effigies @bendhouseart thank you for looking into this whenever you have the time :)

2022-03-19 15:34 UTC, tsalo requested changes
The tests look solid to me. I can definitely see what you mean about it being hard to write tests for these functions though. Validating long string outputs isn't straightforward.

The only thing I would recommend is adding docstrings to the test functions, to make it clear what is actually being tested. For example, `test_make_suffix_table` makes sure that a subset of suffixes and their "long" names appears in a rendered suffix table.

2022-03-22 04:09 UTC, TheChymera commented
@tsalo thank you for the review. I added docstrings as requested — including some commentary re robustness or fragility, which might become useful as the schema structure evolves. Should I go ahead and merge them into one?

2022-03-22 14:39 UTC, tsalo commented
It looks good to me, but we require two approvals before merging, so I'm requesting reviews from Chris and Remi.

2022-03-24 20:18 UTC, effigies approved these changes

2022-03-24 20:18 UTC, merged