[FIX] Clarify that electrodes.tsv is optional for MEG, for use with simultaneous (i)EEG
bids-standard/bids-specification pull request #1555
Opened 2023-07-14 13:12 UTC by effigies

Fixes https://github.com/bids-standard/bids-specification/issues/1550.

2023-07-14 14:10 UTC, robertoostenveld approved these changes
I approve.

2023-07-20 13:09 UTC, sappelhoff requested changes
(placing this here as a visual block, as this is not yet ready IMHO)

2023-08-21 10:10 UTC, sappelhoff reviewed
What do you think about this?

> perhaps we should add a section about `electrodes.tsv` to the [MEG section of the BIDS specification](https://bids-specification.readthedocs.io/en/latest/modality-specific-files/magnetoencephalography.html), and make corresponding schema adjustments.

- https://github.com/bids-standard/bids-specification/issues/1550#issuecomment-1643896148

I see that you have opted for not adding a new section and instead adding this information under `Recording EEG simultaneously with MEG`. I think I'd be fine with that as well.

2023-08-21 10:10 UTC, sappelhoff commented on src/schema/rules/checks/meg.yaml
> +MEGElectrodesRecommended:
as outlined in https://github.com/bids-standard/bids-specification/issues/1550#issuecomment-1686032272, I think this should be optional --> this electrode information **can** also be stored in `_headshape.<ext>` files or sometimes in the data file format itself (Elekta/Neuromag/MEGIN).

2023-08-21 10:10 UTC, sappelhoff commented on src/modality-specific-files/magnetoencephalography.md
> +(see [Coordinate System JSON](#coordinate-system-json-_coordsystemjson) below and
this whole section should be rephrased to account for simultaneous recording with **i**EEG as well.

Simple adjustments like:

```diff
-Recording EEG simultaneously with MEG
+Recording (i)EEG simultaneously with MEG
```

etc.

2023-08-21 10:10 UTC, sappelhoff commented on src/modality-specific-files/magnetoencephalography.md
> +Furthermore, EEG sensor coordinates SHOULD be recorded in an
IMHO the SHOULD should become a MAY.

So far, the spec allowed for recording electrode positions in the `_headshape`: https://bids-specification.readthedocs.io/en/stable/glossary.html#headshape-suffixes

2023-08-24 17:13 UTC, sappelhoff approved these changes

2023-08-24 18:01 UTC, merged