[FIX] Correct PDw suffix description
bids-standard/bids-specification pull request #1578
Opened 2023-08-08 14:14 UTC by jeremie-fouquet

Fixes #1572.

2023-08-08 14:29 UTC, effigies approved these changes
This looks right to me. @agahkarakuzu Could I bug you for a second opinion?

2023-08-22 20:02 UTC, jhlegarreta commented
I'm not an expert on sequences/contrast generation, but looks good to me.

2023-08-24 17:58 UTC, effigies commented
@ericearl https://radiopaedia.org/articles/proton-density-weighted-spin-echo-images-1

2023-08-24 19:01 UTC, ericearl commented
@effigies and @jeremie-fouquet I forgot to tag you. See suggestion/comment above.

2023-08-24 19:25 UTC, effigies commented
@ericearl You may have a review draft comment that didn't get posted.

2023-08-24 22:14 UTC, ericearl requested changes
@effigies Did this post the changes?

2023-08-31 19:20 UTC, effigies commented on src/schema/objects/suffixes.yaml
> +    a long repetition time, a small flip angle, or both.
Looks good to me. WDYT @jeremie-fouquet?

2023-10-27 07:59 UTC, sappelhoff approved these changes
Given that there is some contention (https://github.com/bids-standard/bids-specification/pull/1578#discussion_r1304742957) about the additions, I suggest that **given the additions being an add-on**, we merge this PR, and potentially (if @ericearl wishes) open the **add-on** as a new PR, as also suggested my @jeremie-fouquet in https://github.com/bids-standard/bids-specification/pull/1578#discussion_r1320452068

2023-10-27 08:04 UTC, sappelhoff commented
re-requested your review @effigies so that you can make an assessment of my comment (https://github.com/bids-standard/bids-specification/pull/1578#pullrequestreview-1701206043) and directly merge if you deem appropriate. (With @ericearl currently being away)

2023-10-27 16:15 UTC, nicholst commented on src/schema/objects/suffixes.yaml
> +    a long repetition time, a small flip angle, or both.
What about Eric's text, minus the absolute times, plus a mention that "; also, for gradient echo, this weighting is also possible with a short TR (TR<<T1) and a small flip angle."?

2023-10-31 14:29 UTC, effigies commented on src/schema/objects/suffixes.yaml
> +    a long repetition time, a small flip angle, or both.
```suggestion
    This contrast is achieved at short echo times and long repetition times;
    for gradient echo, this weighting is also possible with a short TR (TR<<T1) and a small flip angle.
```

2023-10-31 14:32 UTC, effigies approved these changes
Applied Tom's suggestion. @ericearl @jeremie-fouquet please review and let us know what you think. In the absence of an objection, we will merge on Monday (Nov 6).

2023-11-03 18:07 UTC, jeremie-fouquet reviewed
Looks correct to me. Thank you.

2023-11-03 18:09 UTC, effigies commented
Alright, let's get this in. Thank you for your patience!

2023-11-03 18:10 UTC, merged

2023-11-03 18:11 UTC, effigies commented
@jeremie-fouquet please be sure to add/update your information in https://github.com/bids-standard/bids-specification/wiki/Recent-Contributors!