[FIX] Hierarchical Event Descriptors (HED) page update
bids-standard/bids-specification pull request #1623
Opened 2023-09-29 13:00 UTC by effigies

Squashed #1592 without some merge noise that reverted unrelated changes.

@tpatpa @VisLab Can you please review to make sure I didn't lose any of the originally planned changes?

Closes #1592.

2023-09-29 15:20 UTC, dorahermes approved these changes

2023-10-01 20:36 UTC, VisLab commented on src/appendices/hed.md
> +(Duration/0.6 s, Sensory-event, Visual-presentation,
This is not correct without the curly brace notation, which is not yet supported by the HED javascript validator used in bids.  Until that all goes through, the annotation for the presentation cannot be enclosed in parentheses:

```code
Duration/0.6 s, Sensory-event, Visual-presentation, 
((Square, Red), (Computer-screen, Center-of)),
```

@effigies can you correct.  Tal will not be available for a while.

2023-10-01 20:40 UTC, VisLab commented on src/appendices/hed.md
> +HED also allows you to use one or more specialized vocabulary along with or instead of
I think this should be vocabularies not vocabulary  because of the "more".

2023-10-01 20:43 UTC, VisLab commented on src/appendices/hed.md
> +
Add:

> A partnered schema is one whose vocabulary trees are merged with its standard schema partner when the
> schema is released. Thus, the two vocabularies appear as one vocabulary to the annotator.

2023-10-01 20:48 UTC, VisLab commented on src/appendices/hed.md
> +The `sc:` is a user-chosen prefix used to distinguish the sources
The `sc:` is a user-chosen prefix used to distinguish the source schemas

2023-10-01 20:51 UTC, VisLab requested changes
I've requested a few minor corrections. Thx!

2023-10-02 01:23 UTC, effigies commented
@VisLab Updated with your suggestions (or minor variations thereon). Please LMK what you think.

2023-10-02 13:07 UTC, VisLab approved these changes
LGTM

2023-10-02 13:19 UTC, merged