[MISC] Add shellcheck checks to ensure that those few shell scripts we have are "robust"
bids-standard/bids-specification pull request #1774
Opened 2024-04-12 18:19 UTC by yarikoptic

TODO
- [ ] remove TEMP commit and possibly a custom workflow if pre-commit picks it up too

2024-04-13 07:46 UTC, Remi-Gau requested changes

2024-04-13 07:47 UTC, Remi-Gau commented on .github/workflows/shellcheck.yml
> +---
would probably also make sense to clean up our CI to remove GHA that duplicate precommit-CI checks

2024-04-13 08:09 UTC, yarikoptic commented on .github/workflows/shellcheck.yml
> +---
Yeap, will remove that commit when get to keyboard again
Thanks!

2024-04-13 15:03 UTC, yarikoptic commented on .github/workflows/shellcheck.yml
> +---
done, pushed! resolving this conversation

2024-04-13 15:05 UTC, yarikoptic commented
oh, actually I have a problem with current pre-commit  setup - it requires docker so fails now
```
ShellCheck v0.9.0........................................................Failed
- hook id: shellcheck
- exit code: 1

Executable `docker` not found
```

keeping it in draft, hopefully would come back to this.

2024-04-15 06:52 UTC, Remi-Gau commented on .pre-commit-config.yaml
adding the following at the end of the pre-commit config should prevent the ci failure but you may need to bring back your GHA workflow. Sorry. 🙈 


```yaml
ci:
  skip: [hadolint-docker]``
```

2024-04-15 13:41 UTC, yarikoptic commented on .pre-commit-config.yaml
did you mean me to add specifically

```
ci:
   skip: [shellcheck]
```
? will try that now

no problem re workflow -- can resurrect it easily

2024-04-15 13:49 UTC, Remi-Gau commented on .pre-commit-config.yaml
ha yes sorry

```yml
ci:
   skip: [shellcheck]
```

2024-04-15 14:50 UTC, Remi-Gau approved these changes

2024-04-15 16:22 UTC, yarikoptic commented on .pre-commit-config.yaml
done that -- pre-commit is happy, shellcheck CI is happy. upload of coverage only unhappy,  but probably unrelated, and likely because from a fork?

2024-04-27 03:20 UTC, yarikoptic commented
@effigies @sappelhoff - an easy one to reduce number of open prs by 1

2024-04-27 07:06 UTC, sappelhoff approved these changes

2024-05-16 01:55 UTC, yarikoptic commented
do we need more approvals here or could it be merged??  it is just a check to make a world a better place!  @effigies do the honors - be the 3rd and press the button?

2024-05-16 08:48 UTC, sappelhoff commented
Thanks for the ping @yarikoptic, we can merge this with two positive reviews and 5 days passed since the last change.

2024-05-16 08:48 UTC, merged

2024-05-16 13:51 UTC, yarikoptic commented
> Thanks for the ping @yarikoptic, we can merge this with two positive reviews and 5 days passed since the last change.

Could/should we automate that ? (e.g. 3 positive reviews and 5 days -- auto-merge)

2024-05-16 15:15 UTC, Remi-Gau commented
We have an old issue, maybe closed, about automating this that was never acted upon because no big need, no big motivation to implement.

2024-05-16 15:45 UTC, yarikoptic commented
drafted one in https://github.com/bids-standard/bids-specification/pull/1823 for now

2024-05-16 15:50 UTC, sappelhoff commented
> We have an old issue, maybe closed, about automating this that was never acted upon because no big need, no big motivation to implement.

- https://github.com/bids-standard/bids-specification/issues/147