[DOC] basic explaination on how to use metadata table macros
bids-standard/bids-specification pull request #840
Opened 2021-07-30 16:33 UTC by Remi-Gau

fixes #838 

This is not perfect but provides some guidance on how to use the metadata table macros.

2021-08-02 07:41 UTC, sappelhoff reviewed
some wording suggestions, overall LGTM

2021-08-02 07:41 UTC, sappelhoff commented on CONTRIBUTING.md
> +We use mkdocs macros to more easily make consistent the style of certain elements of the spec.
```suggestion
We use [mkdocs-macros](https://mkdocs-macros-plugin.readthedocs.io/en/latest/)
to render parts of the BIDS specification from the BIDS schema.
Macros make it easy to achieve a consistent style throughout the specification,
and changing a given macro will automatically change all appropriate paragraphs in the specification.

```

2021-08-02 07:41 UTC, sappelhoff commented on CONTRIBUTING.md
> +to put in the tables from the [yaml files](src/schema/metadata) in the [schema](src/schema/README.md).
```suggestion
For example, all tables on BIDS metadata are generated via macros that make use of data in the
[yaml files](src/schema/metadata) in the [schema](src/schema/README.md).
```

2021-08-02 07:41 UTC, sappelhoff commented on CONTRIBUTING.md
> +where you want output of the macro to be inserted.
```suggestion
The macros are written in Python
(see the folders [tools/schemacode](tools/schemacode) and [tools/mkdocs_macros_bidsschema](tools/mkdocs_macros_bidsschema)),
and are called directly in the Markdown document where you want the output of the macro to be inserted.
```

2021-08-02 07:41 UTC, sappelhoff commented on CONTRIBUTING.md
> +([here](src/schema/metadata/SamplingFrequency.yaml) and [there](src/schema/metadata/StartTime.yaml)).
```suggestion
This macro will create a table for the "SamplingFrequency" and "StartTime" metadata,
filling the table with the content specified in their respective yaml files
(see [SamplingFrequency.yaml](src/schema/metadata/SamplingFrequency.yaml) and [StartTime.yaml](src/schema/metadata/StartTime.yaml)).
```

2021-08-02 07:41 UTC, sappelhoff commented on CONTRIBUTING.md
> +Some of the content created by the macro can specified in the macro call.
```suggestion
Some of the content created by the macro can specified in the macro call itself, as opposed to in the yaml files. 
```

2021-08-02 12:00 UTC, sappelhoff approved these changes

2021-08-08 15:33 UTC, tsalo requested changes
Just one minor typo. Other than that it looks great!

2021-08-08 15:33 UTC, tsalo commented on CONTRIBUTING.md
> +Some of the content created by the macro can specified in the macro call itself, as opposed to in the yaml files.
```suggestion
Some of the content created by the macro can be specified in the macro call itself, as opposed to in the yaml files. 
```

2021-08-09 15:46 UTC, tsalo approved these changes
LGTM. Thanks!

2021-08-09 15:47 UTC, merged

2021-08-09 15:47 UTC, sappelhoff commented
Thanks @Remi-Gau