[FIX] update definition acq_time for sessions.tsv
bids-standard/bids-specification pull request #986
Opened 2022-01-23 07:56 UTC by Remi-Gau

fixes #948 

- [x] simplify `acq_time` definition by removing sections that are redundant with the Unit section
- [x] give different restrictions for scans.tsv and sessions.tsv

2022-01-23 09:41 UTC, sappelhoff approved these changes
Thanks! This is how I imagined it as well. 👍 Let's see what Taylor says about pulling schema description out of the schema and into the macro call.

2022-02-01 15:45 UTC, tsalo requested changes
I'm not sure what the best way to describe this is, but I do think that the description needs to have meaningful information about the field, or else efforts like BIDS-Terms and our glossary won't be very effective. I almost think that it would be better to split the definition into multiple senses if there's no way to write a single interpretable description that only undergoes _minor_ modifications in the tables.

WDYT of just using `acc_time__sessions` and `acq_time__scans`?

2022-02-01 15:45 UTC, tsalo commented on src/03-modality-agnostic-files.md
> +      "acq_time": ("OPTIONAL", "Acquisition time refers to when the first data point in each run was acquired. Furthermore, if this header is provided, the acquisition times of all files that to a re
```suggestion
      "acq_time": ("OPTIONAL", "Acquisition time refers to when the first data point in each run was acquired. Furthermore, if this header is provided, the acquisition times of all files from the same recording MUST be identical."),
```

2022-02-01 15:45 UTC, tsalo commented on src/schema/objects/columns.yaml
> +  description: Datetime format and their anonymization are described in [Units](/02-common-principles.html#units).
```suggestion
  description: |
    The acquisition time for the first data point in each element of the file. 
    The datetime format and its anonymization are described in [Units](/02-common-principles.html#units).
```

2022-02-01 18:29 UTC, tsalo commented on src/schema/objects/columns.yaml
> +  description: Datetime format and their anonymization are described in [Units](/02-common-principles.html#units).
Per today's maintainers call, splitting the definitions is probably the way to go, so you can ignore this suggestion.

2022-02-03 20:12 UTC, Remi-Gau commented
@tsalo I think this should  be done.

2022-02-03 20:13 UTC, tsalo approved these changes
LGTM!

2022-02-04 08:48 UTC, merged

2022-02-04 08:48 UTC, sappelhoff commented
Thanks @Remi-Gau